### ISSUE TITLE
Implement basic refactoring

### ISSUE THREAD

**Issue by walleXD** [walleXD/class2hooks#5]
### ToDo
- [X] Sketch out basic checks for initial run
- [X] Implement `runChecks` 18afeef7e8d8b494def7e94ca0fbc4fff4a1f80e
- [ ] Sketch out & implement `getRefactorables`
- [ ] Sketch out transformation strategies
- [ ] Implement transformation strategies

**Comment by aarondtaveras** [comment]
`api.report` is not a function error in utils.ts. Error received when trying to test `hasComponentDidMount` methods.

**Comment by walleXD** [comment]
@aarondtaveras check out the [jscodeshift docs](
https://github.com/facebook/jscodeshift#api). It being injected by it
